# 📊 Campus Placement Analytics

## 01 - Data Loading & Validation using Python

### Objective
This notebook focuses on loading the cleaned engineering placement dataset, verifying data quality, inspecting the dataset structure, and preparing the data for Exploratory Data Analysis (EDA).

### Tools Used
- Python
- Pandas
- NumPy

### Dataset
Engineering Placement Dataset

In [1]:
# Import required libraries

import pandas as pd
import numpy as np

## 1. Load Dataset

Load the cleaned placement dataset into a Pandas DataFrame.

In [2]:
df = pd.read_csv("C:/Users/Asus/OneDrive/Desktop/Campus_Placement_Analytics/Dataset/Engineering_Placement_Dataset.csv")

## 2. Display First Five Records

Preview the dataset to verify that it has been loaded correctly.

In [3]:
df.head()

,Student_ID,Gender,Branch,Graduation_Year,Class_10_Percentage,Class_12_Percentage,CGPA,Active_Backlogs,Internship,Projects,Certifications,Placement_Status,Company,Job_Role,Package_LPA,Placement_Type,Placement_Season,Location
0,ENG0001,Female,Computer Science & Engineering,2025,90.45,95.53,8.55,1,No,0,1,Placed,Accenture,Data Analyst,7.83,On-Campus,December,Bengaluru
1,ENG0002,Male,Electronics & Communication Engineering,2023,75.96,79.74,6.44,1,Yes,1,2,Placed,EXL,Business Analyst,12.41,On-Campus,October,Kolkata
2,ENG0003,Female,Computer Science & Engineering,2025,60.08,66.52,5.50,2,No,2,0,Not Placed,NaN,NaN,0.00,NaN,NaN,NaN
3,ENG0004,Female,Computer Science & Engineering,2024,67.86,79.30,6.86,1,Yes,2,0,Placed,Accenture,Business Analyst,7.46,On-Campus,December,Bengaluru
4,ENG0005,Male,Electrical Engineering,2021,93.37,93.32,7.67,1,No,2,0,Not Placed,NaN,NaN,0.00,NaN,NaN,NaN

## 3. Dataset Dimensions

Determine the number of rows and columns in the dataset.

In [4]:
print(f"Number of Rows : {df.shape[0]}")
print(f"Number of Columns : {df.shape[1]}")

Number of Rows : 1000
Number of Columns : 18

## 4. Column Names

Display all column names available in the dataset.

In [5]:
df.columns

Index(['Student_ID', 'Gender', 'Branch', 'Graduation_Year',
       'Class_10_Percentage', 'Class_12_Percentage', 'CGPA', 'Active_Backlogs',
       'Internship', 'Projects', 'Certifications', 'Placement_Status',
       'Company', 'Job_Role', 'Package_LPA', 'Placement_Type',
       'Placement_Season', 'Location'],
      dtype='object')

## 5. Dataset Information

Inspect data types, non-null values, and memory usage.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           1000 non-null   object
 1   Gender               1000 non-null   object
 2   Branch               1000 non-null   object
 3   Graduation_Year      1000 non-null   int64
 4   Class_10_Percentage  1000 non-null   float64
 5   Class_12_Percentage  1000 non-null   float64
 6   CGPA                 1000 non-null   float64
 7   Active_Backlogs      1000 non-null   int64
 8   Internship           1000 non-null   object
 9   Projects             1000 non-null   int64
 10  Certifications       1000 non-null   int64
 11  Placement_Status     1000 non-null   object
 12  Company              625 non-null    object
 13  Job_Role             625 non-null    object
 14  Package_LPA          1000 non-null   float64
 15  Placement_Type       625 non-null    object
 16  Placement_Season     625 non-null    object
 17  Location             625 non-null    object
dtypes: float64(4), int64(4), object(10)
memory usage: 140.8+ KB

## 6. Statistical Summary

Generate descriptive statistics for numerical columns.

In [7]:
df.describe()

,Graduation_Year,Class_10_Percentage,Class_12_Percentage,CGPA,Active_Backlogs,Projects,Certifications,Package_LPA
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,2023.134000,82.017470,81.218380,7.298610,0.528000,2.032000,1.486000,6.388040
std,1.349023,7.781814,8.740874,0.867851,0.752185,1.685769,1.351899,6.710545
min,2021.000000,60.000000,54.890000,5.000000,0.000000,0.000000,0.000000,0.000000
25%,2022.000000,76.617500,75.322500,6.730000,0.000000,1.000000,0.000000,0.000000
50%,2023.000000,82.070000,81.155000,7.320000,0.000000,2.000000,1.000000,6.270000
75%,2024.000000,87.350000,87.200000,7.870000,1.000000,3.000000,2.000000,9.732500
max,2025.000000,99.000000,98.000000,9.950000,4.000000,8.000000,6.000000,32.150000

## 7. Summary of Categorical Columns

Display summary statistics for categorical features.

In [8]:
df.describe(include="object")

,Student_ID,Gender,Branch,Internship,Placement_Status,Company,Job_Role,Placement_Type,Placement_Season,Location
count,1000,1000,1000,1000,1000,625,625,625,625,625
unique,1000,2,8,2,2,43,11,3,8,10
top,ENG0001,Male,Computer Science & Engineering,Yes,Placed,Capgemini,Graduate Engineer Trainee,On-Campus,December,Ahmedabad
freq,1,620,219,531,625,39,161,378,93,75

## 8. Missing Value Analysis

Check for missing values in each column.

In [9]:
df.isnull().sum()

Student_ID               0
Gender                   0
Branch                   0
Graduation_Year          0
Class_10_Percentage      0
Class_12_Percentage      0
CGPA                     0
Active_Backlogs          0
Internship               0
Projects                 0
Certifications           0
Placement_Status         0
Company                375
Job_Role               375
Package_LPA              0
Placement_Type         375
Placement_Season       375
Location               375
dtype: int64

## 9. Duplicate Record Check

Verify whether duplicate rows exist in the dataset.

In [10]:
df.duplicated().sum()

np.int64(0)

## 10. Duplicate Student ID Check

Ensure that every student has a unique Student_ID.

In [11]:
df["Student_ID"].duplicated().sum()

np.int64(0)

## 11. Verify Data Types

Display the data type of each column.

In [12]:
df.dtypes

Student_ID              object
Gender                  object
Branch                  object
Graduation_Year          int64
Class_10_Percentage    float64
Class_12_Percentage    float64
CGPA                   float64
Active_Backlogs          int64
Internship              object
Projects                 int64
Certifications           int64
Placement_Status        object
Company                 object
Job_Role                object
Package_LPA            float64
Placement_Type          object
Placement_Season        object
Location                object
dtype: object

## 12. Unique Values in Categorical Columns

Inspect the unique values to verify data consistency.

In [13]:
categorical_columns = [
    "Gender",
    "Branch",
    "Internship",
    "Placement_Status",
    "Placement_Type",
    "Placement_Season"
]

for col in categorical_columns:
    print(f"\n{col}")
    print(df[col].unique())

Gender
['Female' 'Male']

Branch
['Computer Science & Engineering'
 'Electronics & Communication Engineering' 'Electrical Engineering'
 'Architecture' 'Information Technology' 'Mechanical Engineering'
 'Chemical Engineering' 'Civil Engineering']

Internship
['No' 'Yes']

Placement_Status
['Placed' 'Not Placed']

Placement_Type
['On-Campus' nan 'Off-Campus' 'Pool Campus']

Placement_Season
['December' 'October' nan 'February' 'September' 'November' 'March'
 'August' 'January']

## 13. Verify Numeric Columns

Generate summary statistics for numerical features.

In [14]:
numeric_columns = [
    "Class_10_Percentage",
    "Class_12_Percentage",
    "CGPA",
    "Active_Backlogs",
    "Projects",
    "Certifications",
    "Package_LPA"
]

df[numeric_columns].describe()

,Class_10_Percentage,Class_12_Percentage,CGPA,Active_Backlogs,Projects,Certifications,Package_LPA
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,82.017470,81.218380,7.298610,0.528000,2.032000,1.486000,6.388040
std,7.781814,8.740874,0.867851,0.752185,1.685769,1.351899,6.710545
min,60.000000,54.890000,5.000000,0.000000,0.000000,0.000000,0.000000
25%,76.617500,75.322500,6.730000,0.000000,1.000000,0.000000,0.000000
50%,82.070000,81.155000,7.320000,0.000000,2.000000,1.000000,6.270000
75%,87.350000,87.200000,7.870000,1.000000,3.000000,2.000000,9.732500
max,99.000000,98.000000,9.950000,4.000000,8.000000,6.000000,32.150000

## 14. Placement Status Distribution

Display the number of placed and not placed students.

In [15]:
df["Placement_Status"].value_counts()

Placement_Status
Placed        625
Not Placed    375
Name: count, dtype: int64

## 15. Verify Package Distribution

Check the minimum, maximum, and average salary package offered.

In [16]:
print("Minimum Package :", df.loc[df["Placement_Status"]=="Placed","Package_LPA"].min())

print("Maximum Package :", df.loc[df["Placement_Status"]=="Placed","Package_LPA"].max())

print("Average Package :", round(df.loc[df["Placement_Status"]=="Placed","Package_LPA"].mean(),2))

Minimum Package : 3.54
Maximum Package : 32.15
Average Package : 10.22

## 16. Save Verified Dataset

Export the verified dataset for further analysis if required.

In [17]:
df.to_csv("Engineering_Placement_Final.csv", index=False)

# Conclusion

The engineering placement dataset was successfully loaded and verified.

### Validation Summary

- ✅ Dataset loaded successfully.
- ✅ Data types verified.
- ✅ No duplicate student IDs detected.
- ✅ Missing values inspected.
- ✅ Numerical columns validated.
- ✅ Categorical values verified.
- ✅ Salary package values confirmed.
- ✅ Dataset is ready for Exploratory Data Analysis (EDA).

The validated dataset will be used in the next notebook to perform detailed exploratory data analysis and visualization.