# 📊 Campus Placement Analytics

# 02 - Exploratory Data Analysis (EDA)

## Objective

Perform exploratory data analysis on the engineering placement dataset using Python and Pandas to uncover placement trends, academic performance, package distribution, and relationships between key variables.

### Tools Used

- Python
- Pandas
- NumPy

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("C:/Users/Asus/OneDrive/Desktop/Campus_Placement_Analytics/Python/Engineering_Placement_Final.csv")

df.head()

,Student_ID,Gender,Branch,Graduation_Year,Class_10_Percentage,Class_12_Percentage,CGPA,Active_Backlogs,Internship,Projects,Certifications,Placement_Status,Company,Job_Role,Package_LPA,Placement_Type,Placement_Season,Location
0,ENG0001,Female,Computer Science & Engineering,2025,90.45,95.53,8.55,1,No,0,1,Placed,Accenture,Data Analyst,7.83,On-Campus,December,Bengaluru
1,ENG0002,Male,Electronics & Communication Engineering,2023,75.96,79.74,6.44,1,Yes,1,2,Placed,EXL,Business Analyst,12.41,On-Campus,October,Kolkata
2,ENG0003,Female,Computer Science & Engineering,2025,60.08,66.52,5.50,2,No,2,0,Not Placed,NaN,NaN,0.00,NaN,NaN,NaN
3,ENG0004,Female,Computer Science & Engineering,2024,67.86,79.30,6.86,1,Yes,2,0,Placed,Accenture,Business Analyst,7.46,On-Campus,December,Bengaluru
4,ENG0005,Male,Electrical Engineering,2021,93.37,93.32,7.67,1,No,2,0,Not Placed,NaN,NaN,0.00,NaN,NaN,NaN

## Placement Distribution

Analyze the proportion of placed and not placed students.

In [5]:
df["Placement_Status"].value_counts()

Placement_Status
Placed        625
Not Placed    375
Name: count, dtype: int64

### Observation

Most students were successfully placed.
The remaining students were not placed.

## Academic Performance

Calculate average Class 10, Class 12 percentage and CGPA.

In [6]:
df[
[
"Class_10_Percentage",
"Class_12_Percentage",
"CGPA"
]
].mean().round(2)

Class_10_Percentage    82.02
Class_12_Percentage    81.22
CGPA                    7.30
dtype: float64

## Average CGPA by Placement Status

In [7]:
df.groupby("Placement_Status")["CGPA"].mean().round(2)

Placement_Status
Not Placed    6.75
Placed        7.63
Name: CGPA, dtype: float64

### Observation

Placed students generally have a higher average CGPA.

## Projects Completed

In [8]:
df.groupby("Placement_Status")["Projects"].mean().round(2)

Placement_Status
Not Placed    1.44
Placed        2.39
Name: Projects, dtype: float64

### Observation

Placed students tend to complete more academic projects.

## Certifications Analysis

In [9]:
df.groupby("Placement_Status")["Certifications"].mean().round(2)

Placement_Status
Not Placed    1.07
Placed        1.73
Name: Certifications, dtype: float64

### Observation

Students with placements generally possess more certifications.

## Internship Experience

In [10]:
pd.crosstab(
df["Internship"],
df["Placement_Status"],
margins=True
)

Placement_Status  Not Placed  Placed   All
Internship
No                       280     189   469
Yes                       95     436   531
All                      375     625  1000

### Observation

Students with internship experience show higher placement counts.

## Active Backlogs Analysis

In [11]:
pd.crosstab(
df["Active_Backlogs"],
df["Placement_Status"]
)

Placement_Status  Not Placed  Placed
Active_Backlogs
0                        131     472
1                        141     149
2                         82       4
3                         18       0
4                          3       0

### Observation

Placement likelihood decreases as active backlogs increase.

## Salary Package Statistics

In [12]:
placed=df[df["Placement_Status"]=="Placed"]

placed["Package_LPA"].describe()

count    625.000000
mean      10.220864
std        5.732015
min        3.540000
25%        6.590000
50%        8.430000
75%       11.600000
max       32.150000
Name: Package_LPA, dtype: float64

## Top 10 Highest Salary Packages

In [13]:
placed.nlargest(
10,"Package_LPA")[
["Student_ID","Branch","Company","Package_LPA"]
]

    Student_ID                                   Branch Company  Package_LPA
599    ENG0600                   Information Technology  Google        32.15
170    ENG0171  Electronics & Communication Engineering  Google        32.10
156    ENG0157           Computer Science & Engineering  Google        31.93
643    ENG0644           Computer Science & Engineering  Google        31.67
663    ENG0664           Computer Science & Engineering  Google        31.64
18     ENG0019           Computer Science & Engineering   Adobe        30.41
936    ENG0937  Electronics & Communication Engineering  Amazon        30.01
725    ENG0726           Computer Science & Engineering  Google        29.59
775    ENG0776  Electronics & Communication Engineering  Google        29.40
968    ENG0969  Electronics & Communication Engineering  Google        29.01

## Branch-wise Placement Count

In [14]:
placed["Branch"].value_counts()

Branch
Computer Science & Engineering             143
Electronics & Communication Engineering    118
Information Technology                      81
Mechanical Engineering                      73
Civil Engineering                           65
Electrical Engineering                      64
Chemical Engineering                        42
Architecture                                39
Name: count, dtype: int64

## Most Common Job Roles

In [15]:
placed["Job_Role"].value_counts()

Job_Role
Graduate Engineer Trainee    161
Data Analyst                  86
Software Engineer             82
QA Engineer                   59
Business Analyst              58
Civil Engineer                36
DevOps Engineer               34
Mechanical Engineer           34
Data Engineer                 32
Electrical Engineer           26
Architect                     17
Name: count, dtype: int64

## Top Recruiting Companies

In [16]:
placed["Company"].value_counts().head(10)

Company
Capgemini             39
L&T                   36
Infosys               35
Wipro                 35
Cognizant             33
Accenture             33
TCS                   28
Shapoorji Pallonji    24
DLF                   23
Siemens               21
Name: count, dtype: int64

## Placement Season Analysis

In [17]:
placed["Placement_Season"].value_counts()

Placement_Season
December     93
January      93
November     92
October      81
February     69
March        68
August       67
September    62
Name: count, dtype: int64

## Placement Locations

In [18]:
placed["Location"].value_counts()

Location
Ahmedabad     75
Pune          73
Kolkata       69
Bengaluru     69
Delhi NCR     60
Mumbai        59
Coimbatore    59
Noida         59
Hyderabad     53
Chennai       49
Name: count, dtype: int64

## Correlation Analysis

In [19]:
corr=df.select_dtypes(
include=["int64","float64"]
).corr()

corr.round(2)

,Graduation_Year,Class_10_Percentage,Class_12_Percentage,CGPA,Active_Backlogs,Projects,Certifications,Package_LPA
Graduation_Year,1.00,-0.01,-0.01,0.02,-0.01,0.03,0.01,-0.00
Class_10_Percentage,-0.01,1.00,0.64,0.50,-0.12,0.04,0.06,0.16
Class_12_Percentage,-0.01,0.64,1.00,0.75,-0.18,0.03,0.08,0.24
CGPA,0.02,0.50,0.75,1.00,-0.29,0.26,0.31,0.42
Active_Backlogs,-0.01,-0.12,-0.18,-0.29,1.00,-0.14,-0.09,-0.35
Projects,0.03,0.04,0.03,0.26,-0.14,1.00,0.21,0.24
Certifications,0.01,0.06,0.08,0.31,-0.09,0.21,1.00,0.22
Package_LPA,-0.00,0.16,0.24,0.42,-0.35,0.24,0.22,1.00

# Key Insights

### Major Findings

- More than half of the students secured placements.
- Students with higher CGPA generally achieved better placement outcomes.
- Internship experience positively influences placement success.
- Students completing more projects and certifications show better placement performance.
- Salary packages vary across companies and branches.
- Active backlogs negatively affect placement opportunities.
- Correlation analysis indicates that CGPA, projects, and certifications have a positive relationship with placement success.